// Generated by ui_designer.py — compilable VortexOS GUI program.
#include <gui/libwidget.h>
static char textbox1_buf[32];
static Widget ws[] = {
    { WD_BUTTON, 0, 0, 120, 36, "Button", guiRgb(255,255,255), guiRgb(60,110,200), guiRgb(20,40,90), 0, 0, 0, 0, 0 },
    { WD_LABEL, 0, 42, 120, 20, "Label", guiRgb(40,40,40), guiRgb(0,0,0), guiRgb(0,0,0), 0, 0, 0, 0, 0 },
    { WD_TEXTBOX, 0, 66, 180, 28, "text", guiRgb(20,20,20), guiRgb(255,255,255), guiRgb(120,120,120), 0, textbox1_buf, 32, 0, 0 },
    { WD_CHECKBOX, 0, 106, 140, 22, "Check", guiRgb(40,40,40), guiRgb(255,255,255), guiRgb(120,120,120), 0, 0, 0, 0, 1 },
    { WD_LINE, 0, 134, 200, 2, "", guiRgb(0,0,0), guiRgb(0,0,0), guiRgb(180,180,180), 0, 0, 0, 0, 0 },
    { WD_RECT, 0, 159, 200, 60, "", guiRgb(0,0,0), guiRgb(0,0,0), guiRgb(140,140,140), 0, 0, 0, 0, 0 }
};
#define N (sizeof(ws)/sizeof(ws[0]))
void _start(void) {
    int win = guiCreateWindow("My UI", 120, 90, 360, 240, guiRgb(60,80,170), guiRgb(240,240,240), WM_STYLE_DEFAULT);
    if (win < 0) guiExit();
    wdInit(ws, N);
    int focus = -1;
    int prevDown = 0;
    wdDraw(win, ws, N); guiFlush();
    for (;;) {
        WmEvent ev; guiPoll(&ev);
        if (ev.key == KEY_ESC) break;
        int wx, wy; guiGetWinPos(win, &wx, &wy);
        int mx = ev.mouseX - wx;
        int my = ev.mouseY - wy - WM_TITLEBAR_H;
        int changed = 0;
        int down = ev.leftDown;
        if (!down && prevDown) {
            /* 松开沿: 结束当前组件交互, 复位按钮按下态 */
            if (focus >= 0) changed = wdPress(win, ws, N, focus, 0);
        } else if (down && !prevDown) {
            /* 按下沿: 命中并开始交互(复选在此切换, 文本框获焦) */
            int idx = wdHit(ws, N, mx, my);
            if (idx >= 0) { focus = idx; changed = wdPress(win, ws, N, idx, 1); }
            else focus = -1;
        }
        prevDown = down;
        changed |= wdHandleKey(win, ws, N, &focus, ev.key);
        if (changed) { wdDraw(win, ws, N); guiFlush(); }
    }
    guiExit();
}
